### ISSUE TITLE
Feature Request - Anzeige der SEO Preview in der Seitenstruktur

### ISSUE THREAD

**Issue by csaeum** [exatre/contao-seo_preview#2]
Hallo ich würde es gut finden wenn in der Seitenstruktur es ersichtlich wäre, wie gut die Titel usw sind.
Also einfach eine Ampel die wie beim SEO-Preview anzeigt ob es rot, gelb oder grün ist.

Als 2tes wäre es noch besser wenn es eine 2tes Icon gibt, das anzeigt ob die Daten automatisch oder von Hand eingetragen wurde.

Wieso das, ich will gerade viele Seiten von Hand optimieren, leider wird es nach x Stunden unübersichtlich welches man schon hat und welches nicht.

Hätte man nun ein Icon das anzeigt ob die Daten von Hand eingetragen worden sind, wüsste ich "Ok da warste schon"
Wenn man zusätzlich noch die Ampel hätte, wüsste man "Ok die sind von Hand eingetragen aber da ist noch ein (Fehler)"

Wäre super wenn du es umsetzen könntest.

![vorschlag-seo-preview](https://cloud.githubusercontent.com/assets/1543510/8634593/c6c7587a-27fe-11e5-9596-c3c6d7ce2f08.PNG)

**Comment by valentin-** [comment]
Hi,

werden Titel und Beschreibung nicht immer "per Hand" eingetragen? Was meinst du mit automatisch?
Ein Ampelsystem macht sicher Sinn, werde ich mir ansehen.

**Comment by valentin-** [comment]
Wie soll das Ampelsystem funktionieren? Ist es notwendig in der Übersicht die Zeichenlänge der Felder zu überprüfen? Oder reicht die Überprüfung, ob Titel und Beschreibung vorhanden sind?

**Comment by csaeum** [comment]
Zu deinen ersten Beitrag, klar sollten die immer von Hand eingetragen werden. Aber Ich habe bei mir gerade sehr viele Seiten kopiert und umbenannt, die davor hatten noch keine Titel & Beschreibungen (zum Glück).
Nach dem kopieren (150 Seiten) mussten diese dann Stück für Stück aufgebaut werden. Ich musste strukturiert vor gehen, hier wäre ein Ampelsystem super:

Vielleicht mit diesen Funktionen:
Rot = Title & Beschreibung sind leer oder werden mit Standard gefüllt
Gelb = Titel oder Beschreibung ist ausgefüllt
Grün = Beide sind ausgefüllt.

Als Zusatz kann man ja vielleicht noch eine 2te anfügen.
Rot = Titel oder Beschreibung sind zu lange oder automatisch gefüllt
Gelb = Titel oder Beschreibung (sind Gelb oder nur eines ausgeüllt)
Grün = Beide sind in der richtigen Länge ausgefüllt

Das 1te ist die schnelle und Standardlösung,
Das 2te wäre die feinere Lösung weil hier wird nicht nur klar ob ausgefüllt sondern auch wie lange die Texte sind. Auf der Seite selbst stellst du es ja schon in den Farben da. 
Man müsste halt nur einen Cron machen der dann diese Felder abfragt und dann eine Kennzahl in eine DB schreibt was er hier dann darstellen soll.

Hoffe ich habe es gut dargestellt.

**Comment by valentin-** [comment]
Sorry hat etwas gedauert, Update ist eingespielt: https://community.contao.org/de/showthread.php?56048-SEO_preview-Suchmaschinen-Vorschau&p=399971&viewfull=1#post399971
